### Registration new user
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "User",
    "email": "user@gmail.com",
    "password":"qwerty",
    "phone": "+38000000000"
}

### Authorization User
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "qwerty"
}

### Get current user
GET http://localhost:3000/api/me
Authorization: 

### Update current user
PUT http://localhost:3000/api/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblR5cGUiOiJUT0tFTl9UWVBFX0FDQ0VTUyIsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJpZCI6OSwicGhvbmUiOiIrMzgwMDAwMDAwMDAiLCJpYXQiOjE1MzgzNTA3MjgsImV4cCI6MTUzODQzNzEyOCwic3ViIjoiOSJ9.W7D7ieriFSFNEwmCg112m6D-NhWzox9FICO_g12VN8lQnJCIC8oQWd7GM1PcEF4mnCFC53KnnstmW6B3N8kQGA

{
    "phone": "+38000100000",
    "name": "Bla", 
    "email": "user@gmail.com", 
    "current_password": "qwerty", 
    "new_password": "bla" 
}

### Get user by Id
GET http://localhost:3000/api/user/1
Authorization: 

### Search user
GET http://localhost:3000/api/user?name=user&email=user@gmail.com

### Create item
PUT http://localhost:3000/api/item
Content-Type: application/json
Authorization: 

{
    "title": "Awesome work",
    "description": "Awesome project"
}
### Delete item by Id
DELETE http://localhost:3000/api/item/1
Authorization: 

### Get item by Id
GET http://localhost:3000/api/item/2

### Upload item image
POST http://localhost:3000/api/item/1/image
Authorization: 
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="iAm.png"
Content-Type: image/jpeg

< ./images/iAm.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
### Search items
GET http://localhost:3000/api/item?title=Awesome+work&user_id=2&order_by=created_at&order_type=asc
### Update item
PUT http://localhost:3000/api/item/1
Content-Type: application/json
Authorization: 

{
    "title": "bla",
    "description": "bla" 
}
### Remove item image
DELETE http://localhost:3000/api/item/1/image
Authorization: 
